### ISSUE TITLE
Update Uno.Wasm.Bootstrap to latest version 7.x

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#318]
### Describe the bug

# Background
In #297, we updated all Uno libraries to the latest version, except for [Uno.Wasm.Bootstrap](https://www.nuget.org/packages/Uno.Wasm.Bootstrap). 

According to the Uno Platform team:

> Uno.Wasm.Bootstrap 3.x is .NET6, and is using emscripten 2.0.23: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/fc89b40db92a14b8f04d4c5c9c72690bdcd7b878/src/Uno.Wasm.Bootstrap/Constants.cs#L19
> 
> Uno.Wasm.Bootstrap 7.x is .NET7, and is using emscripten 3.1.12: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/55a871e6ed4a255a93631f75d9edb6362356adbe/src/Uno.Wasm.Bootstrap/Constants.cs#L19

During #297, we found that `Rive.RiveSharp` could not be used with `Uno.Wasm.Bootstrap` 3.x as it was compiled with another version. This was corrected in #306.

# The problem
Labs is still using Uno.Wasm.Bootstrap 3.x, but needs to be using the latest version.

### Steps to reproduce

```text
n/a
```

### Expected behavior

n/a

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, but only if others can assist.

**Comment by Arlodotexe** [comment]
This is also blocking our investigation into fixing the Rive experiment in Release mode on WASM.

**Comment by michael-hawker** [comment]
Related to https://github.com/rive-app/rive-sharp/issues/4

https://github.com/CommunityToolkit/Labs-Windows/pull/328 was failing to update to SkiaSharp.Views.WinUI 2.88.3 (with enscripten updates) due to https://github.com/mono/SkiaSharp/issues/2272

So I think this means we need to wait until we update the Windows App SDK references in #183 or for a SkiaSharp update?

**Comment by Arlodotexe** [comment]
I've updated us to the latest version of SkiaSharp. Testing in a codespace, I'm seeing this error:

```
Exception Encountered Loading file 'ms-appx:///SourceAssets/CanvasLayout/samples/CanvasLayout.Samples/CanvasLayout.md':
The file [/SourceAssets/CanvasLayout/samples/CanvasLayout.Samples/CanvasLayout.md] cannot be found
   at Windows.Storage.Helpers.AssetsManager.DownloadAsset(CancellationToken ct, String assetPath) in /home/vsts/work/1/s/src/Uno.UWP/Storage/Helpers/AssetsManager.wasm.cs:line 88
   at Windows.Storage.StorageFile.GetFileFromApplicationUri(CancellationToken ct, Uri uri) in /home/vsts/work/1/s/src/Uno.UWP/Storage/StorageFile.wasm.cs:line 30
   at Windows.Foundation.AsyncOperation`1.<BuildTaskAsync>d__5[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.Foundation/AsyncOperation.TResult.cs:line 47
   at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__11`1[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in /home/vsts/work/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
   at CommunityToolkit.Labs.Shared.Renderers.ToolkitDocumentationRenderer.GetDocumentationFileContents(ToolkitFrontMatter metadata) in /workspaces/Labs-Windows/common/CommunityToolkit.Labs.Shared/Renderers/ToolkitDocumentationRenderer.xaml.cs:line 186
```

Putting this aside for now, will investigate in more detail later.
